"""Public catalog service with stable DTOs and replaceable data source."""

from __future__ import annotations

from schemas.category import (
    CategoryItem,
    CategoryListResponse,
    InfluencerCatalogResponse,
    InfluencerListItem,
    PlatformItem,
    PlatformListResponse,
)
from schemas.common import PaginationMeta

CATALOG_CATEGORIES = [
    CategoryItem(id="all", label="Hammasi", image="🌟"),
    CategoryItem(id="finance", label="Moliya", image="💰"),
    CategoryItem(id="psychology", label="Psixologiya", image="🧠"),
    CategoryItem(id="development", label="Rivojlanish", image="📈"),
    CategoryItem(id="programming", label="Dasturlash", image="💻"),
    CategoryItem(id="lifestyle", label="Lifestyle", image="☕"),
    CategoryItem(id="beauty", label="Go'zallik", image="✨"),
    CategoryItem(id="humor", label="Yumor", image="😂"),
    CategoryItem(id="business", label="Biznes", image="💼"),
    CategoryItem(id="family", label="Oilaviy", image="👨‍👩‍👧‍👦"),
    CategoryItem(id="medicine", label="Tibbiyot", image="🏥"),
    CategoryItem(id="kids", label="Bolalar", image="👶"),
    CategoryItem(id="nature", label="Tabiat", image="🌿"),
    CategoryItem(id="travel", label="Sayohat", image="✈️"),
    CategoryItem(id="education", label="Ta'lim", image="📚"),
    CategoryItem(id="gaming", label="O'yinlar", image="🎮"),
    CategoryItem(id="sport", label="Sport", image="⚽"),
]

CATALOG_PLATFORMS: list[PlatformItem] = [
    PlatformItem(id="all", label="Barchasi"),
    PlatformItem(id="instagram", label="Instagram"),
    PlatformItem(id="telegram", label="Telegram"),
    PlatformItem(id="youtube", label="YouTube"),
    PlatformItem(id="tiktok", label="TikTok"),
]

CATALOG_INFLUENCERS = [
    InfluencerListItem(
        id="tg-webmakon",
        name="Webmakon",
        handle="webmakon",
        platform="telegram",
        category="tech",
        followers=68000,
        rating=4.9,
        price=40,
        image_url="/influencers/webmakon.jpg",
        is_top=True,
        location="Toshkent",
        bio="O'zbekistondagi dasturlash va veb-texnologiyalar bo'yicha top Telegram kanal. Kod, freymvorklar va IT bozori yangiliklari.",
        engagement_rate=18.2,
    ),
    InfluencerListItem(
        id="tg-asroriskandarovshb",
        name="Asror Iskandarov",
        handle="asroriskandarovshb",
        platform="telegram",
        category="business",
        followers=32000,
        rating=4.8,
        price=25,
        image_url="/influencers/asroriskandarovshb.jpg",
        is_top=False,
        location="Toshkent",
        bio="Tadbirkorlik, investitsiya va shaxsiy rivojlanish bo'yicha fikr va tahlillar. Startap va biznes ekotizimi haqida.",
        engagement_rate=14.5,
    ),
    InfluencerListItem(
        id="tg-temurbek_adhamov",
        name="Temurbek Adhamov",
        handle="temurbek_adhamov",
        platform="telegram",
        category="business",
        followers=38000,
        rating=4.7,
        price=30,
        image_url="/influencers/temurbek_adhamov.jpg",
        is_top=False,
        location="Toshkent",
        bio="Marketing, raqamli iqtisodiyot va tadbirkorlik bo'yicha amaliy maslahatlar. O'zbek biznes jamoasining faol a'zosi.",
        engagement_rate=16.3,
    ),
    InfluencerListItem(
        id="tg-alisherrustamov",
        name="Alisher Rustamov",
        handle="alisherrustamov",
        platform="telegram",
        category="business",
        followers=62000,
        rating=4.8,
        price=45,
        image_url="/influencers/alisherrustamov.jpg",
        is_top=False,
        location="Toshkent",
        bio="SMM, kontent marketing va ijtimoiy tarmoqlar orqali biznes qurishning amaliy usullari.",
        engagement_rate=12.8,
    ),
    InfluencerListItem(
        id="tg-mfaktoruz",
        name="M Faktor UZ",
        handle="MFaktorUZ",
        platform="telegram",
        category="lifestyle",
        followers=185000,
        rating=4.7,
        price=80,
        image_url="/influencers/mfaktoruz.jpg",
        is_top=True,
        location="Toshkent",
        bio="O'zbekistondagi eng ommabop kontent kanallaridan biri. Hayot tarzi, yangiliklar va qiziqarli kontent.",
        engagement_rate=10.4,
    ),
    InfluencerListItem(
        id="tg-kunuz",
        name="Kun.uz",
        handle="kunuz",
        platform="telegram",
        category="education",
        followers=650000,
        rating=4.8,
        price=350,
        image_url="/influencers/kunuz.jpg",
        is_top=True,
        location="Toshkent",
        bio="O'zbekistonning yetakchi internet nashri Kun.uz'ning Telegram kanali. Eng tezkor va ishonchli yangiliklar.",
        engagement_rate=8.5,
    ),
    InfluencerListItem(
        id="tg-daryo",
        name="Daryo.uz",
        handle="daryo",
        platform="telegram",
        category="education",
        followers=920000,
        rating=4.7,
        price=450,
        image_url="/influencers/daryo.jpg",
        is_top=True,
        location="Toshkent",
        bio="O'zbekistonda eng ko'p o'qiladigan internet portallaridan biri. Yangiliklar, tahlillar va intervyular.",
        engagement_rate=7.2,
    ),
    InfluencerListItem(
        id="tg-qalampir",
        name="Qalampir.uz",
        handle="qalampir",
        platform="telegram",
        category="education",
        followers=380000,
        rating=4.6,
        price=200,
        image_url="/influencers/qalampir.jpg",
        is_top=True,
        location="Toshkent",
        bio="Ijtimoiy ommaviy axborot vositasi — yangiliklar, jarayonlar va qiziqarli tadqiqotlar.",
        engagement_rate=9.1,
    ),
    InfluencerListItem(
        id="tg-xushnudbek",
        name="Xushnudbek",
        handle="xushnudbek",
        platform="telegram",
        category="lifestyle",
        followers=42000,
        rating=4.6,
        price=30,
        image_url="https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Shaxsiy blog — hayot tajribasi, sayohat va fikrlar. Samimiy va tabiiy kontent.",
        engagement_rate=20.1,
    ),
    InfluencerListItem(
        id="tg-shaxzod_blog",
        name="Shaxzod Blog",
        handle="shaxzod_blog",
        platform="telegram",
        category="lifestyle",
        followers=28000,
        rating=4.5,
        price=20,
        image_url="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Kundalik hayot, motivatsiya va shaxsiy tajriba haqidagi samimiy blog.",
        engagement_rate=22.5,
    ),
    InfluencerListItem(
        id="tg-sardorbek_germany",
        name="Sardorbek Germany",
        handle="sardorbek_germany",
        platform="telegram",
        category="education",
        followers=55000,
        rating=4.9,
        price=40,
        image_url="https://images.unsplash.com/photo-1559761919-8111e06c5db4?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Berlin, DE",
        bio="Germaniyada yashash, ishlash va ta'lim olish haqida birinchi qo'ldan ma'lumot. Viza, til va emigratsiya yo'llanmasi.",
        engagement_rate=24.3,
    ),
    InfluencerListItem(
        id="tg-germaniya_visa",
        name="Germaniya Viza",
        handle="Germaniya_visa",
        platform="telegram",
        category="education",
        followers=82000,
        rating=4.8,
        price=50,
        image_url="https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Berlin, DE",
        bio="Germaniyaga viza, o'qish va ko'chib o'tish bo'yicha rasmiy ma'lumotlar va tajriba ulashish kanali.",
        engagement_rate=19.7,
    ),
    InfluencerListItem(
        id="tg-articles365",
        name="Articles 365",
        handle="articles365",
        platform="telegram",
        category="education",
        followers=45000,
        rating=4.7,
        price=35,
        image_url="https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Fan, texnologiya va dunyodagi o'zgarishlar haqida qisqa va mazmunli maqolalar. Har kuni yangi bilim.",
        engagement_rate=15.8,
    ),
    InfluencerListItem(
        id="tg-baxodirjon_mullajonov",
        name="Baxodirjon Mullajonov",
        handle="Baxodirjon_Mullajonov",
        platform="telegram",
        category="business",
        followers=48000,
        rating=4.7,
        price=35,
        image_url="https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Raqamli marketing, e-commerce va farovon hayot uchun moliyaviy strategiyalar bo'yicha nufuzli blog.",
        engagement_rate=13.4,
    ),
    InfluencerListItem(
        id="tg-kanallani_dodasi",
        name="Kanallani Dodasi",
        handle="kanallani_dodasi",
        platform="telegram",
        category="humor",
        followers=92000,
        rating=4.6,
        price=55,
        image_url="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Toshkent",
        bio="Kanallar aggregatori va Telegram duniyasidagi eng qiziqarli kontent. Hazil, ma'lumot va foydali kanallar.",
        engagement_rate=11.2,
    ),
    InfluencerListItem(
        id="tg-uzbek_shou_biznes",
        name="Uzbek Show Biznes",
        handle="uzbek_shou_biznes",
        platform="telegram",
        category="lifestyle",
        followers=125000,
        rating=4.5,
        price=65,
        image_url="https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="O'zbek estradasi, kino va show-biznesdagi eng so'nggi yangiliklar va gossiplar.",
        engagement_rate=12.7,
    ),
    InfluencerListItem(
        id="tg-top_faktlar",
        name="Top Faktlar",
        handle="top_faktlar",
        platform="telegram",
        category="education",
        followers=108000,
        rating=4.6,
        price=55,
        image_url="https://images.unsplash.com/photo-1503551723145-6c040742065b?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Dunyodagi eng qiziqarli va kutilmagan faktlar. Fan, tarix va texnologiyadan hayratlanarli misollar.",
        engagement_rate=13.9,
    ),
    InfluencerListItem(
        id="tg-prikollar_olami",
        name="Prikollar Olami",
        handle="prikollar_olami",
        platform="telegram",
        category="humor",
        followers=210000,
        rating=4.4,
        price=90,
        image_url="https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="O'zbek Telegram'idagi eng yirik kulgili kontent kanali. Hazil, meme va video prikollar.",
        engagement_rate=15.6,
    ),
    InfluencerListItem(
        id="tg-ingliz_tili_uz",
        name="Ingliz Tili UZ",
        handle="ingliz_tili_uz",
        platform="telegram",
        category="education",
        followers=215000,
        rating=4.9,
        price=90,
        image_url="https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Toshkent",
        bio="Ingliz tilini o'zbek tilida o'rganishning eng oson yo'li. Grammatika, so'z boyligi va amaliy mashqlar.",
        engagement_rate=17.4,
    ),
    InfluencerListItem(
        id="tg-goethe_uzbekistan",
        name="Goethe-Institut Uzbekistan",
        handle="goethe_uzbekistan",
        platform="telegram",
        category="education",
        followers=18500,
        rating=4.8,
        price=40,
        image_url="https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Germaniya madaniyati va nemis tilini O'zbekistonda targ'ib qiluvchi rasmiy Goethe-Institut kanali.",
        engagement_rate=8.9,
    ),
    InfluencerListItem(
        id="tg-uzedu",
        name="UzEdu",
        handle="uzedu",
        platform="telegram",
        category="education",
        followers=88000,
        rating=4.7,
        price=50,
        image_url="https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="O'zbekistondagi ta'lim tizimi yangiliklari, universitetlar va abituriyentlar uchun foydali ma'lumotlar.",
        engagement_rate=14.2,
    ),
    InfluencerListItem(
        id="tg-grantlar_uz",
        name="Grantlar UZ",
        handle="grantlar_uz",
        platform="telegram",
        category="education",
        followers=132000,
        rating=4.9,
        price=65,
        image_url="https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Toshkent",
        bio="Xorijda o'qish imkoniyatlari, grantlar va stipendiyalar haqida O'zbekistondagi yetakchi kanal.",
        engagement_rate=21.3,
    ),
    InfluencerListItem(
        id="tg-pazandachilik",
        name="Pazandachilik",
        handle="pazandachilik",
        platform="telegram",
        category="lifestyle",
        followers=265000,
        rating=4.8,
        price=110,
        image_url="https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Toshkent",
        bio="O'zbek va jahon taomlari retseptlari. Fotosuratlar bilan har kuni yangi, tasdiqlangan retseptlar.",
        engagement_rate=16.8,
    ),
    InfluencerListItem(
        id="tg-ayollar_sahifasi",
        name="Ayollar Sahifasi",
        handle="ayollar_sahifasi",
        platform="telegram",
        category="lifestyle",
        followers=188000,
        rating=4.7,
        price=85,
        image_url="https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Zamonaviy o'zbek ayoli uchun: moda, sog'liq, oila va psixologik maslahatlar.",
        engagement_rate=15.3,
    ),
    InfluencerListItem(
        id="tg-retseptlar_olami",
        name="Retseptlar Olami",
        handle="retseptlar_olami",
        platform="telegram",
        category="lifestyle",
        followers=138000,
        rating=4.6,
        price=65,
        image_url="https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Oddiy va tezkor taomlar retseptlari. Har kuni yangi retsept — uyda ham, bayramda ham.",
        engagement_rate=18.9,
    ),
    InfluencerListItem(
        id="tg-tribunauz",
        name="Tribuna.uz",
        handle="tribunauz",
        platform="telegram",
        category="sport",
        followers=420000,
        rating=4.8,
        price=200,
        image_url="https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Toshkent",
        bio="O'zbekistonning sport portali Tribuna.uz'ning rasmiy kanali. Futbol, boks va milliy sport yangiliklari.",
        engagement_rate=11.4,
    ),
    InfluencerListItem(
        id="tg-sportuz_official",
        name="Sport.uz",
        handle="sportuz_official",
        platform="telegram",
        category="sport",
        followers=255000,
        rating=4.7,
        price=120,
        image_url="https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="O'zbekiston sport yangiliklari, natijalar va statistikalar. Milliy jamoalar va xalqaro musobaqalar.",
        engagement_rate=9.8,
    ),
    InfluencerListItem(
        id="tg-championatasia",
        name="Championat Asia",
        handle="championatasia",
        platform="telegram",
        category="sport",
        followers=95000,
        rating=4.6,
        price=60,
        image_url="https://images.unsplash.com/photo-1486286701208-1d58e9338013?q=80&w=400&auto=format&fit=crop",
        is_top=False,
        location="Toshkent",
        bio="Osiyo va O'rta Osiyo sport chempionatlari, AFC va AFF musobaqalari haqida tezkor yangiliklar.",
        engagement_rate=13.2,
    ),
    InfluencerListItem(
        id="tg-avtouz_bozor",
        name="Avto.uz Bozor",
        handle="avtouz_bozor",
        platform="telegram",
        category="tech",
        followers=162000,
        rating=4.5,
        price=75,
        image_url="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=400&auto=format&fit=crop",
        is_top=True,
        location="Toshkent",
        bio="O'zbekistondagi avtomobil bozori — sotilgan va sotuvdagi mashinalar, narxlar va ekspert baholari.",
        engagement_rate=10.7,
    ),
]


class CatalogService:
    """Provides stable catalog DTOs independent of persistence details."""

    def list_categories(self) -> CategoryListResponse:
        return CategoryListResponse(items=CATALOG_CATEGORIES)

    def list_platforms(self) -> PlatformListResponse:
        return PlatformListResponse(items=CATALOG_PLATFORMS)

    def list_influencers(
        self,
        *,
        platform: str | None = None,
        category: str | None = None,
        query: str | None = None,
        only_top: bool = False,
        limit: int = 24,
        offset: int = 0,
    ) -> InfluencerCatalogResponse:
        normalized_query = query.lower().strip() if query else None
        filtered = [
            item
            for item in CATALOG_INFLUENCERS
            if (not platform or platform == "all" or item.platform == platform)
            and (not category or category == "all" or item.category == category)
            and (not only_top or item.is_top)
            and (
                not normalized_query
                or normalized_query in item.name.lower()
                or normalized_query in item.handle.lower()
                or normalized_query in item.category.lower()
            )
        ]

        paginated = filtered[offset : offset + limit]
        meta = PaginationMeta(total=len(filtered), limit=limit, offset=offset)
        return InfluencerCatalogResponse(items=paginated, meta=meta)


catalog_service = CatalogService()
