import type { Influencer } from "@/domain/influencer/types";

/**
 * ═══════════════════════════════════════════════════════
 * REKLAMER — HAQIQIY O'ZBEKISTON INFLUENSERLARI
 * ═══════════════════════════════════════════════════════
 *
 * Bu ma'lumotlar haqiqiy kanallar asosida to'ldirilgan.
 * Obunachi soni taxminiy (2024-yil ma'lumotlari).
 * Narxlar O'zbekiston bozori o'rtacha bahosi (USD, 1 post).
 *
 * Real ma'lumotlarni olish uchun:
 *   Telegram → /backend/scripts/fetch_telegram_stats.py
 *   YouTube  → /backend/scripts/fetch_youtube_stats.py
 */

export const mockInfluencers: Influencer[] = [

  // ═══════════════════════════════════════════
  // BIZNES / TEXNOLOGIYA / IT
  // ═══════════════════════════════════════════
  {
    id: "tg-webmakon",
    name: "Webmakon",
    handle: "webmakon",
    platform: "telegram",
    category: "tech",
    followers: 68000,
    rating: 4.9,
    price: 40,
    isTop: true,
    location: "Toshkent",
    bio: "O'zbekistondagi dasturlash va veb-texnologiyalar bo'yicha top Telegram kanal. Kod, freymvorklar va IT bozori yangiliklari.",
    engagementRate: 18.2,
    socialUrl: "https://t.me/webmakon",
    imageUrl: "/influencers/webmakon.jpg",
  },
  {
    id: "tg-asroriskandarovshb",
    name: "Asror Iskandarov",
    handle: "asroriskandarovshb",
    platform: "telegram",
    category: "business",
    followers: 32000,
    rating: 4.8,
    price: 25,
    location: "Toshkent",
    bio: "Tadbirkorlik, investitsiya va shaxsiy rivojlanish bo'yicha fikr va tahlillar. Startap va biznes ekotizimi haqida.",
    engagementRate: 14.5,
    socialUrl: "https://t.me/asroriskandarovshb",
    imageUrl: "/influencers/asroriskandarovshb.jpg",
  },
  {
    id: "tg-temurbek_adhamov",
    name: "Temurbek Adhamov",
    handle: "temurbek_adhamov",
    platform: "telegram",
    category: "business",
    followers: 38000,
    rating: 4.7,
    price: 30,
    location: "Toshkent",
    bio: "Marketing, raqamli iqtisodiyot va tadbirkorlik bo'yicha amaliy maslahatlar. O'zbek biznes jamoasining faol a'zosi.",
    engagementRate: 16.3,
    socialUrl: "https://t.me/temurbek_adhamov",
    imageUrl: "/influencers/temurbek_adhamov.jpg",
  },
  {
    id: "tg-alisherrustamov",
    name: "Alisher Rustamov",
    handle: "alisherrustamov",
    platform: "telegram",
    category: "business",
    followers: 62000,
    rating: 4.8,
    price: 45,
    location: "Toshkent",
    bio: "SMM, kontent marketing va ijtimoiy tarmoqlar orqali biznes qurishning amaliy usullari.",
    engagementRate: 12.8,
    socialUrl: "https://t.me/alisherrustamov",
    imageUrl: "/influencers/alisherrustamov.jpg",
  },
  {
    id: "tg-mfaktoruz",
    name: "M Faktor UZ",
    handle: "MFaktorUZ",
    platform: "telegram",
    category: "lifestyle",
    followers: 185000,
    rating: 4.7,
    price: 80,
    isTop: true,
    location: "Toshkent",
    bio: "O'zbekistondagi eng ommabop kontent kanallaridan biri. Hayot tarzi, yangiliklar va qiziqarli kontent.",
    engagementRate: 10.4,
    socialUrl: "https://t.me/MFaktorUZ",
    imageUrl: "/influencers/mfaktoruz.jpg",
  },

  // ═══════════════════════════════════════════
  // YANGILIKLAR / AXBOROT
  // ═══════════════════════════════════════════
  {
    id: "tg-kunuz",
    name: "Kun.uz",
    handle: "kunuz",
    platform: "telegram",
    category: "education",
    followers: 650000,
    rating: 4.8,
    price: 350,
    isTop: true,
    verified: true,
    location: "Toshkent",
    bio: "O'zbekistonning yetakchi internet nashri Kun.uz'ning Telegram kanali. Eng tezkor va ishonchli yangiliklar.",
    engagementRate: 8.5,
    socialUrl: "https://t.me/kunuz",
    imageUrl: "/influencers/kunuz.jpg",
  },
  {
    id: "tg-daryo",
    name: "Daryo.uz",
    handle: "daryo",
    platform: "telegram",
    category: "education",
    followers: 920000,
    rating: 4.7,
    price: 450,
    isTop: true,
    verified: true,
    location: "Toshkent",
    bio: "O'zbekistonda eng ko'p o'qiladigan internet portallaridan biri. Yangiliklar, tahlillar va intervyular.",
    engagementRate: 7.2,
    socialUrl: "https://t.me/daryo",
    imageUrl: "/influencers/daryo.jpg",
  },
  {
    id: "tg-qalampir",
    name: "Qalampir.uz",
    handle: "qalampir",
    platform: "telegram",
    category: "education",
    followers: 380000,
    rating: 4.6,
    price: 200,
    isTop: true,
    location: "Toshkent",
    bio: "Ijtimoiy ommaviy axborot vositasi — yangiliklar, jarayonlar va qiziqarli tadqiqotlar.",
    engagementRate: 9.1,
    socialUrl: "https://t.me/qalampir",
    imageUrl: "/influencers/qalampir.jpg",
  },
  {
    id: "tg-xushnudbek",
    name: "Xushnudbek",
    handle: "xushnudbek",
    platform: "telegram",
    category: "lifestyle",
    followers: 42000,
    rating: 4.6,
    price: 30,
    location: "Toshkent",
    bio: "Shaxsiy blog — hayot tajribasi, sayohat va fikrlar. Samimiy va tabiiy kontent.",
    engagementRate: 20.1,
    socialUrl: "https://t.me/xushnudbek",
    imageUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-shaxzod_blog",
    name: "Shaxzod Blog",
    handle: "shaxzod_blog",
    platform: "telegram",
    category: "lifestyle",
    followers: 28000,
    rating: 4.5,
    price: 20,
    location: "Toshkent",
    bio: "Kundalik hayot, motivatsiya va shaxsiy tajriba haqidagi samimiy blog.",
    engagementRate: 22.5,
    socialUrl: "https://t.me/shaxzod_blog",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
  },

  // ═══════════════════════════════════════════
  // GERMANIYA / EMIGRATSIYA
  // ═══════════════════════════════════════════
  {
    id: "tg-sardorbek_germany",
    name: "Sardorbek Germany",
    handle: "sardorbek_germany",
    platform: "telegram",
    category: "education",
    followers: 55000,
    rating: 4.9,
    price: 40,
    isTop: true,
    location: "Berlin, DE",
    bio: "Germaniyada yashash, ishlash va ta'lim olish haqida birinchi qo'ldan ma'lumot. Viza, til va emigratsiya yo'llanmasi.",
    engagementRate: 24.3,
    socialUrl: "https://t.me/sardorbek_germany",
    imageUrl: "https://images.unsplash.com/photo-1559761919-8111e06c5db4?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-germaniya_visa",
    name: "Germaniya Viza",
    handle: "Germaniya_visa",
    platform: "telegram",
    category: "education",
    followers: 82000,
    rating: 4.8,
    price: 50,
    isTop: true,
    location: "Berlin, DE",
    bio: "Germaniyaga viza, o'qish va ko'chib o'tish bo'yicha rasmiy ma'lumotlar va tajriba ulashish kanali.",
    engagementRate: 19.7,
    socialUrl: "https://t.me/Germaniya_visa",
    imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-articles365",
    name: "Articles 365",
    handle: "articles365",
    platform: "telegram",
    category: "education",
    followers: 45000,
    rating: 4.7,
    price: 35,
    location: "Toshkent",
    bio: "Fan, texnologiya va dunyodagi o'zgarishlar haqida qisqa va mazmunli maqolalar. Har kuni yangi bilim.",
    engagementRate: 15.8,
    socialUrl: "https://t.me/articles365",
    imageUrl: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-baxodirjon_mullajonov",
    name: "Baxodirjon Mullajonov",
    handle: "Baxodirjon_Mullajonov",
    platform: "telegram",
    category: "business",
    followers: 48000,
    rating: 4.7,
    price: 35,
    location: "Toshkent",
    bio: "Raqamli marketing, e-commerce va farovon hayot uchun moliyaviy strategiyalar bo'yicha nufuzli blog.",
    engagementRate: 13.4,
    socialUrl: "https://t.me/Baxodirjon_Mullajonov",
    imageUrl: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?q=80&w=400&auto=format&fit=crop",
  },

  // ═══════════════════════════════════════════
  // LIFESTYLE VA O'YIN-KULGI
  // ═══════════════════════════════════════════
  {
    id: "tg-kanallani_dodasi",
    name: "Kanallani Dodasi",
    handle: "kanallani_dodasi",
    platform: "telegram",
    category: "humor",
    followers: 92000,
    rating: 4.6,
    price: 55,
    isTop: true,
    location: "Toshkent",
    bio: "Kanallar aggregatori va Telegram duniyasidagi eng qiziqarli kontent. Hazil, ma'lumot va foydali kanallar.",
    engagementRate: 11.2,
    socialUrl: "https://t.me/kanallani_dodasi",
    imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-uzbek_shou_biznes",
    name: "Uzbek Show Biznes",
    handle: "uzbek_shou_biznes",
    platform: "telegram",
    category: "lifestyle",
    followers: 125000,
    rating: 4.5,
    price: 65,
    location: "Toshkent",
    bio: "O'zbek estradasi, kino va show-biznesdagi eng so'nggi yangiliklar va gossiplar.",
    engagementRate: 12.7,
    socialUrl: "https://t.me/uzbek_shou_biznes",
    imageUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-top_faktlar",
    name: "Top Faktlar",
    handle: "top_faktlar",
    platform: "telegram",
    category: "education",
    followers: 108000,
    rating: 4.6,
    price: 55,
    location: "Toshkent",
    bio: "Dunyodagi eng qiziqarli va kutilmagan faktlar. Fan, tarix va texnologiyadan hayratlanarli misollar.",
    engagementRate: 13.9,
    socialUrl: "https://t.me/top_faktlar",
    imageUrl: "https://images.unsplash.com/photo-1503551723145-6c040742065b?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-prikollar_olami",
    name: "Prikollar Olami",
    handle: "prikollar_olami",
    platform: "telegram",
    category: "humor",
    followers: 210000,
    rating: 4.4,
    price: 90,
    location: "Toshkent",
    bio: "O'zbek Telegram'idagi eng yirik kulgili kontent kanali. Hazil, meme va video prikollar.",
    engagementRate: 15.6,
    socialUrl: "https://t.me/prikollar_olami",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=400&auto=format&fit=crop",
  },

  // ═══════════════════════════════════════════
  // TA'LIM VA TIL O'RGANISH
  // ═══════════════════════════════════════════
  {
    id: "tg-ingliz_tili_uz",
    name: "Ingliz Tili UZ",
    handle: "ingliz_tili_uz",
    platform: "telegram",
    category: "education",
    followers: 215000,
    rating: 4.9,
    price: 90,
    isTop: true,
    location: "Toshkent",
    bio: "Ingliz tilini o'zbek tilida o'rganishning eng oson yo'li. Grammatika, so'z boyligi va amaliy mashqlar.",
    engagementRate: 17.4,
    socialUrl: "https://t.me/ingliz_tili_uz",
    imageUrl: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-goethe_uzbekistan",
    name: "Goethe-Institut Uzbekistan",
    handle: "goethe_uzbekistan",
    platform: "telegram",
    category: "education",
    followers: 18500,
    rating: 4.8,
    price: 40,
    verified: true,
    location: "Toshkent",
    bio: "Germaniya madaniyati va nemis tilini O'zbekistonda targ'ib qiluvchi rasmiy Goethe-Institut kanali.",
    engagementRate: 8.9,
    socialUrl: "https://t.me/goethe_uzbekistan",
    imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-uzedu",
    name: "UzEdu",
    handle: "uzedu",
    platform: "telegram",
    category: "education",
    followers: 88000,
    rating: 4.7,
    price: 50,
    location: "Toshkent",
    bio: "O'zbekistondagi ta'lim tizimi yangiliklari, universitetlar va abituriyentlar uchun foydali ma'lumotlar.",
    engagementRate: 14.2,
    socialUrl: "https://t.me/uzedu",
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-grantlar_uz",
    name: "Grantlar UZ",
    handle: "grantlar_uz",
    platform: "telegram",
    category: "education",
    followers: 132000,
    rating: 4.9,
    price: 65,
    isTop: true,
    location: "Toshkent",
    bio: "Xorijda o'qish imkoniyatlari, grantlar va stipendiyalar haqida O'zbekistondagi yetakchi kanal.",
    engagementRate: 21.3,
    socialUrl: "https://t.me/grantlar_uz",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=400&auto=format&fit=crop",
  },

  // ═══════════════════════════════════════════
  // AYOLLAR VA PAZANDALIK
  // ═══════════════════════════════════════════
  {
    id: "tg-pazandachilik",
    name: "Pazandachilik",
    handle: "pazandachilik",
    platform: "telegram",
    category: "lifestyle",
    followers: 265000,
    rating: 4.8,
    price: 110,
    isTop: true,
    location: "Toshkent",
    bio: "O'zbek va jahon taomlari retseptlari. Fotosuratlar bilan har kuni yangi, tasdiqlangan retseptlar.",
    engagementRate: 16.8,
    socialUrl: "https://t.me/pazandachilik",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-ayollar_sahifasi",
    name: "Ayollar Sahifasi",
    handle: "ayollar_sahifasi",
    platform: "telegram",
    category: "lifestyle",
    followers: 188000,
    rating: 4.7,
    price: 85,
    location: "Toshkent",
    bio: "Zamonaviy o'zbek ayoli uchun: moda, sog'liq, oila va psixologik maslahatlar.",
    engagementRate: 15.3,
    socialUrl: "https://t.me/ayollar_sahifasi",
    imageUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-retseptlar_olami",
    name: "Retseptlar Olami",
    handle: "retseptlar_olami",
    platform: "telegram",
    category: "lifestyle",
    followers: 138000,
    rating: 4.6,
    price: 65,
    location: "Toshkent",
    bio: "Oddiy va tezkor taomlar retseptlari. Har kuni yangi retsept — uyda ham, bayramda ham.",
    engagementRate: 18.9,
    socialUrl: "https://t.me/retseptlar_olami",
    imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=400&auto=format&fit=crop",
  },

  // ═══════════════════════════════════════════
  // SPORT
  // ═══════════════════════════════════════════
  {
    id: "tg-tribunauz",
    name: "Tribuna.uz",
    handle: "tribunauz",
    platform: "telegram",
    category: "sport",
    followers: 420000,
    rating: 4.8,
    price: 200,
    isTop: true,
    verified: true,
    location: "Toshkent",
    bio: "O'zbekistonning sport portali Tribuna.uz'ning rasmiy kanali. Futbol, boks va milliy sport yangiliklari.",
    engagementRate: 11.4,
    socialUrl: "https://t.me/tribunauz",
    imageUrl: "https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-sportuz_official",
    name: "Sport.uz",
    handle: "sportuz_official",
    platform: "telegram",
    category: "sport",
    followers: 255000,
    rating: 4.7,
    price: 120,
    verified: true,
    location: "Toshkent",
    bio: "O'zbekiston sport yangiliklari, natijalar va statistikalar. Milliy jamoalar va xalqaro musobaqalar.",
    engagementRate: 9.8,
    socialUrl: "https://t.me/sportuz_official",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "tg-championatasia",
    name: "Championat Asia",
    handle: "championatasia",
    platform: "telegram",
    category: "sport",
    followers: 95000,
    rating: 4.6,
    price: 60,
    location: "Toshkent",
    bio: "Osiyo va O'rta Osiyo sport chempionatlari, AFC va AFF musobaqalari haqida tezkor yangiliklar.",
    engagementRate: 13.2,
    socialUrl: "https://t.me/championatasia",
    imageUrl: "https://images.unsplash.com/photo-1486286701208-1d58e9338013?q=80&w=400&auto=format&fit=crop",
  },

  // ═══════════════════════════════════════════
  // AVTO
  // ═══════════════════════════════════════════
  {
    id: "tg-avtouz_bozor",
    name: "Avto.uz Bozor",
    handle: "avtouz_bozor",
    platform: "telegram",
    category: "tech",
    followers: 162000,
    rating: 4.5,
    price: 75,
    isTop: true,
    location: "Toshkent",
    bio: "O'zbekistondagi avtomobil bozori — sotilgan va sotuvdagi mashinalar, narxlar va ekspert baholari.",
    engagementRate: 10.7,
    socialUrl: "https://t.me/avtouz_bozor",
    imageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=400&auto=format&fit=crop",
  },
];
